version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir build
      - cp index.html build/
  post_build:
    commands:
      - echo Build completed on `date`
      - cp appspec.yml build/
      - cp script/* build/
artifacts:
  files: '**/*'
  discard-paths: yes
